channels:
  - defaults
  - pytorch
  - fastai
dependencies:
  - pip
  - jupyterlab
  - cudatoolkit==9.0
  - pytorch
  - torchvision
  - tensorflow-gpu
  - keras
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - opencv
  - pillow
  - scikit-image
  - py-xgboost-gpu
  - fastai
  - pip:
    - tableone
