channels:
  - defaults
  - pytorch
dependencies:
  - pip
  - jupyterlab
  - cudatoolkit==9.0
  - pytorch
  - torchvision
  - tensorflow-gpu
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - tableone
    - xgboost
    - fastai
